### ISSUE TITLE
(Location review)

### ISSUE THREAD

**Issue by BeccaB76** [BeeHiveCyberSecurity/BeeHive-Cogs#7]
**What zip code do we need to review?**
If you're receiving incorrect results for a specific zip code/location pair, please let us know the zip code in question.

68501

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by BeeHiveCyberSecurity** [comment]
`68501` has been mapped as `40.818470, -96.710500` and is now avaialble. Thank you! <3
