### ISSUE TITLE
(Bug) AntiPhishing cog doesn't detect masked links

### ISSUE THREAD

**Issue by JpbmOfficial** [BeeHiveCyberSecurity/BeeHive-Cogs#8]
**Describe the bug**
The AntiPhishing cog does not detect malicious links when they're being masked.

**To Reproduce**
1.Created a masked link such as [steamcommunity.com/gift-card/pay/50](https://malicious.link)
2. Post it
3. The bot will say it's legit.
4. Post the same malicious link without being masked, https://malicious.link
5. The bot will say it's malicious and to report it to the staff members.

**Expected behavior**
The bot will detect malicious links even though they're being used as masked links.

**Screenshots**
https://prnt.sc/Jhtwrqbm4rzR

**Comment by BeeHiveCyberSecurity** [comment]
Hi @JpbmOfficial

We've taken the time to change how, URL's are parsed/processed, and are now seeing accurate detections for hyperlinks masked using markdown. These changes are present in version `1.3.6.4`. Please update the version your bot is running to at least `1.3.6.4` and re-test, and let us know if this concern re-presents itself. If we don't hear from you within a week, we'll assume we fixed the issue and you're back to enjoyment.

Thanks!

**Comment by JpbmOfficial** [comment]
Hi!
Thanks a lot for the quick answer and solution.
It is working fine now.
Thanks a lot and have a great weekend!
